# Generated by Django 3.2.13 on 2022-04-21 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuthSMS",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("phone_number", models.CharField(max_length=11)),
                ("code", models.CharField(max_length=6)),
                ("verify", models.DateTimeField(blank=True, null=True)),
                (
                    "type",
                    models.CharField(choices=[("sign_up", "sign_up")], max_length=10),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
