# Generated by Django 3.2.13 on 2022-04-21 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sms", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="authsms",
            options={"ordering": ["-pk"]},
        ),
        migrations.AlterField(
            model_name="authsms",
            name="code",
            field=models.CharField(db_index=True, max_length=6),
        ),
        migrations.AlterField(
            model_name="authsms",
            name="phone_number",
            field=models.CharField(db_index=True, max_length=11),
        ),
        migrations.AlterField(
            model_name="authsms",
            name="verify",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
