# Generated by Django 3.2.13 on 2022-04-23 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sms", "0002_auto_20220421_1639"),
    ]

    operations = [
        migrations.AlterField(
            model_name="authsms",
            name="type",
            field=models.CharField(
                choices=[("sign_up", "회원가입"), ("forgot_password", "비밀번호 찾기")],
                max_length=15,
            ),
        ),
    ]
