# Generated by Django 3.2.13 on 2022-04-20 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_user_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="nickname",
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
