# Generated by Django 3.2.13 on 2022-04-21 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_user_nickname"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(blank=True, max_length=11, null=True, unique=True),
        ),
    ]
