# Generated by Django 3.2.13 on 2022-04-23 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_alter_user_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="name",
            field=models.EmailField(max_length=10),
        ),
    ]
